/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults, RouterHistory } from "@stencil/router";
export namespace Components {
    interface KtEditPage {
        "history": RouterHistory;
        "match": MatchResults;
    }
    interface KtHistoryPage {
        "history": RouterHistory;
        "match": MatchResults;
    }
    interface KtIndexPage {
        "history": RouterHistory;
    }
    interface KtRoot {
    }
    interface KtStatsPage {
        "history": RouterHistory;
        "match": MatchResults;
    }
    interface KtStudyPage {
        "history": RouterHistory;
        "match": MatchResults;
    }
}
declare global {
    interface HTMLKtEditPageElement extends Components.KtEditPage, HTMLStencilElement {
    }
    var HTMLKtEditPageElement: {
        prototype: HTMLKtEditPageElement;
        new (): HTMLKtEditPageElement;
    };
    interface HTMLKtHistoryPageElement extends Components.KtHistoryPage, HTMLStencilElement {
    }
    var HTMLKtHistoryPageElement: {
        prototype: HTMLKtHistoryPageElement;
        new (): HTMLKtHistoryPageElement;
    };
    interface HTMLKtIndexPageElement extends Components.KtIndexPage, HTMLStencilElement {
    }
    var HTMLKtIndexPageElement: {
        prototype: HTMLKtIndexPageElement;
        new (): HTMLKtIndexPageElement;
    };
    interface HTMLKtRootElement extends Components.KtRoot, HTMLStencilElement {
    }
    var HTMLKtRootElement: {
        prototype: HTMLKtRootElement;
        new (): HTMLKtRootElement;
    };
    interface HTMLKtStatsPageElement extends Components.KtStatsPage, HTMLStencilElement {
    }
    var HTMLKtStatsPageElement: {
        prototype: HTMLKtStatsPageElement;
        new (): HTMLKtStatsPageElement;
    };
    interface HTMLKtStudyPageElement extends Components.KtStudyPage, HTMLStencilElement {
    }
    var HTMLKtStudyPageElement: {
        prototype: HTMLKtStudyPageElement;
        new (): HTMLKtStudyPageElement;
    };
    interface HTMLElementTagNameMap {
        "kt-edit-page": HTMLKtEditPageElement;
        "kt-history-page": HTMLKtHistoryPageElement;
        "kt-index-page": HTMLKtIndexPageElement;
        "kt-root": HTMLKtRootElement;
        "kt-stats-page": HTMLKtStatsPageElement;
        "kt-study-page": HTMLKtStudyPageElement;
    }
}
declare namespace LocalJSX {
    interface KtEditPage {
        "history"?: RouterHistory;
        "match"?: MatchResults;
    }
    interface KtHistoryPage {
        "history"?: RouterHistory;
        "match"?: MatchResults;
    }
    interface KtIndexPage {
        "history"?: RouterHistory;
    }
    interface KtRoot {
    }
    interface KtStatsPage {
        "history"?: RouterHistory;
        "match"?: MatchResults;
    }
    interface KtStudyPage {
        "history"?: RouterHistory;
        "match"?: MatchResults;
    }
    interface IntrinsicElements {
        "kt-edit-page": KtEditPage;
        "kt-history-page": KtHistoryPage;
        "kt-index-page": KtIndexPage;
        "kt-root": KtRoot;
        "kt-stats-page": KtStatsPage;
        "kt-study-page": KtStudyPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kt-edit-page": LocalJSX.KtEditPage & JSXBase.HTMLAttributes<HTMLKtEditPageElement>;
            "kt-history-page": LocalJSX.KtHistoryPage & JSXBase.HTMLAttributes<HTMLKtHistoryPageElement>;
            "kt-index-page": LocalJSX.KtIndexPage & JSXBase.HTMLAttributes<HTMLKtIndexPageElement>;
            "kt-root": LocalJSX.KtRoot & JSXBase.HTMLAttributes<HTMLKtRootElement>;
            "kt-stats-page": LocalJSX.KtStatsPage & JSXBase.HTMLAttributes<HTMLKtStatsPageElement>;
            "kt-study-page": LocalJSX.KtStudyPage & JSXBase.HTMLAttributes<HTMLKtStudyPageElement>;
        }
    }
}
